### ISSUE TITLE
Python Task 1, Question 1: Car Matrix Generation

### ISSUE THREAD

**Issue by AbhiRajale** [mapup/MapUp-Data-Assessment-F#24]
The dataset "dataset-1.csv" should have 342 rows, and currently only has 341.

Would you like us to update the missing value as 0, or something else?

**Comment by Shivakumar4380** [comment]
Replace 'dataset-1.csv' with the actual path to your CSV file. This code will check if the CSV file has less than 342 rows and it will append a row filled with zeros to the Data Frame and save the updated Data Frame back to the CSV file.

**Comment by Shivakumar4380** [comment]
Load the CSV file into a Pandas DataFrame
file_path = 'dataset-1.csv'
df = pd.read_csv(file_path)

Check the number of rows before filling the missing value
current_row_count = df.shape[0]
expected_row_count = 342

Check if a row is missing and fill it with 0
if current_row_count < expected_row_count: df = df.append(pd.Series([0]*len(df.columns)), ignore_index=True)

   Save the updated DataFrame back to the CSV file
    df.to_csv(file_path, index=False)

**Comment by ShanamgariVyshnavi** [comment]
Update the Missing Value as 0.

**Comment by Neeraj81** [comment]
Dataset-1.csv should have 342 rows. Where is it written that there should be 342?

**Comment by AbhiRajale** [comment]
Thank you for your inputs. 

I'll submit my files shortly.
